// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrE84vq84dAmfjVISI7ZDqk65HYVTadQU',
    appId: '1:635352733890:web:a67eed223332f0370e435b',
    messagingSenderId: '635352733890',
    projectId: 'gogame-bc5f2',
    authDomain: 'gogame-bc5f2.firebaseapp.com',
    storageBucket: 'gogame-bc5f2.firebasestorage.app',
    measurementId: 'G-VLVYNCG02D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvvsORgL83OtmDp1pceHdQh9CWGMZog5Y',
    appId: '1:635352733890:android:a6697ba2bb32b0410e435b',
    messagingSenderId: '635352733890',
    projectId: 'gogame-bc5f2',
    storageBucket: 'gogame-bc5f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCpzWnLrYFmNZcG00Gx5Ml46DkC8exCaU',
    appId: '1:635352733890:ios:422a267c396173390e435b',
    messagingSenderId: '635352733890',
    projectId: 'gogame-bc5f2',
    storageBucket: 'gogame-bc5f2.firebasestorage.app',
    iosBundleId: 'com.example.gogame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCpzWnLrYFmNZcG00Gx5Ml46DkC8exCaU',
    appId: '1:635352733890:ios:422a267c396173390e435b',
    messagingSenderId: '635352733890',
    projectId: 'gogame-bc5f2',
    storageBucket: 'gogame-bc5f2.firebasestorage.app',
    iosBundleId: 'com.example.gogame',
  );

}